name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: | 
          cd tasks/first-task/
          npm ci
      - name: Lint code
        run: |
          cd tasks/first-task/
          npm run lint
      - name: Test code
        run: |
          cd tasks/first-task/
          npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.file }}
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Install dependencies
        run: |
          cd tasks/first-task/
          npm ci
      - name: Build website
        run: |
          cd tasks/first-task/
          npm run build
      - name: Publish required value
        id: publish
        run: find tasks/first-task/dist/assets/*.js -type f -execdir echo 'file={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist-files
          path: tasks/first-task/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get Build Artifacts
        uses: actions/download-artifact@v7
        with:
          name: dist-files
      - name: Output
        run: ls
      - name: Deploy
        run: echo "${{ needs.build.outputs.script-file }}"
    
